menus:
  - id: ubuntu-22.04.3-live-server-amd64
    menu_text: "Install Ubuntu 22.04 LTS with autoinstaller (MAC: ${mac_addr})"
    #image_id: ubuntu-22.04.3-live-server-amd64

  - id: ubuntu-22.04.3-live-server-amd64-common
    menu_text: Install Ubuntu 22.04 LTS
    #image_id: ubuntu-22.04.3-live-server-amd64

  - id: ubuntu-22.04.3-desktop-amd64-common
    menu_text: Install Ubuntu 22.04 LTS desktop
    #image_id: ubuntu-22.04.3-desktop-amd64

autoinstalls:
  # Template will be copied on the image-server "/os/autoinstall/${id}/user-data".
  - id: common
    template: common.yml.j2

  - id: 52:54:ff:00:00:01
    # This program will search templates under the directory template/
    template: autoinstall_by_mac.yml.j2
    # Args will be passed when the template is rendered.
    args:
      hostname: myubuntu

# images.<id_of_image>.url
images:
  ubuntu-22.04.3-live-server-amd64:
    url: https://releases.ubuntu.com/jammy/ubuntu-22.04.3-live-server-amd64.iso
    #sha256: a4acfda10b18da50e2ec50ccaf860d7f20b389df8765611142305c0e911d16fd
  ubuntu-22.04.3-desktop-amd64:
    url: https://releases.ubuntu.com/jammy/ubuntu-22.04.3-desktop-amd64.iso
    #sha256: a435f6f393dda581172490eda9f683c32e495158a780b5a1de422ee77d98e909
