menus:
  # Sections list of the menu.
  #   id: The id of the menu. It must be unique amoung the sections.
  #   menu_text: The text of the menu that will display on the screen.
  #   image_id: The id of the image. It must be exists in the images section in this file.
  #   custom_imgargs (optional): Arguments that will be passed as imgargs to boot the image.
  #                              If you skipped to specify this, the default imgargs will be used.
  #                              The default imgargs is -
  #                              "imgargs vmlinuz initrd=initrd autoinstall ip=dhcp url=http://${next-server}/os/images/${image_name_prefix}.iso ds=nocloud-net;s=http://${next-server}/os/autoinstall/${mac_addr}/ ---".
  - id: ubuntu-22.04.4-live-server-amd64
    menu_text: "Install Ubuntu 22.04 LTS with autoinstaller (MAC: ${mac_addr})"
    image_id: "ubuntu-22.04.4-live-server-amd64"

  - id: ubuntu-22.04.4-live-server-amd64-common
    menu_text: "Install Ubuntu 22.04 LTS with common autoinstaller"
    image_id: "ubuntu-22.04.4-live-server-amd64"
    custom_imgargs: "imgargs vmlinuz initrd=initrd autoinstall ip=dhcp url=http://${next-server}/os/images/${image_name_prefix}.iso ds=nocloud-net;s=http://${next-server}/os/autoinstall/common/ ---"

  - id: ubuntu-22.04.4-live-server-amd64-intaractive
    menu_text: "Install Ubuntu 22.04 LTS interactively"
    image_id: "ubuntu-22.04.4-live-server-amd64"
    custom_imgargs: "imgargs vmlinuz initrd=initrd autoinstall ip=dhcp url=http://${next-server}/os/images/${image_name_prefix}.iso ---"

  - id: ubuntu-22.04.4-desktop-amd64-intaractive
    menu_text: "Install Ubuntu 22.04 LTS desktop interactively"
    image_id: "ubuntu-22.04.4-desktop-amd64"
    custom_imgargs: "imgargs vmlinuz initrd=initrd autoinstall ip=dhcp url=http://${next-server}/os/images/${image_name_prefix}.iso ---"


  - id: ubuntu-24.04-live-server-amd64
    menu_text: "Install Ubuntu 24.04 LTS with autoinstaller (MAC: ${mac_addr})"
    # Specify the id of images.<id>
    image_id: "ubuntu-24.04-live-server-amd64"

  - id: ubuntu-24.04-live-server-amd64-common
    menu_text: "Install Ubuntu 24.04 LTS with common autoinstaller"
    image_id: "ubuntu-24.04-live-server-amd64"
    custom_imgargs: "imgargs vmlinuz initrd=initrd autoinstall ip=dhcp url=http://${next-server}/os/images/${image_name_prefix}.iso ds=nocloud-net;s=http://${next-server}/os/autoinstall/common/ ---"

  - id: ubuntu-24.04-live-server-amd64-intaractive
    menu_text: "Install Ubuntu 24.04 LTS interactively"
    image_id: "ubuntu-24.04-live-server-amd64"
    custom_imgargs: "imgargs vmlinuz initrd=initrd autoinstall ip=dhcp url=http://${next-server}/os/images/${image_name_prefix}.iso ---"

  - id: ubuntu-24.04-desktop-amd64-intaractive
    menu_text: "Install Ubuntu 24.04 LTS desktop interactively"
    image_id: "ubuntu-24.04-desktop-amd64"
    custom_imgargs: "imgargs vmlinuz initrd=initrd autoinstall ip=dhcp url=http://${next-server}/os/images/${image_name_prefix}.iso ---"

autoinstalls:
  # Template will be copied on the image-server "/os/autoinstall/${id}/user-data".
  - id: common
    template: common.yml.j2

  - id: "52:54:ff:00:00:01"
    # This program will search templates under the directory template/
    template: autoinstall_by_mac.yml.j2
    # Args will be passed when the template is rendered.
    args:
      hostname: ubuntu-server
      network:
        ethernets:
          enp1s0:
            link-local: []
            dhcp4: false
            dhcp6: false
            addresses: ["172.16.1.11/16"]
            gateway4: 172.28.0.1
            nameservers:
              addresses: ["172.31.0.1", "8.8.8.8", "8.8.4.4"]
        version: 2

# images.<id_of_image>.url
images:
  ubuntu-22.04.4-live-server-amd64:
    url: "https://releases.ubuntu.com/jammy/ubuntu-22.04.4-live-server-amd64.iso"
    #sha256: 45f873de9f8cb637345d6e66a583762730bbea30277ef7b32c9c3bd6700a32b2
  ubuntu-22.04.4-desktop-amd64:
    url: "https://releases.ubuntu.com/jammy/ubuntu-22.04.4-desktop-amd64.iso"
    #sha256: 071d5a534c1a2d61d64c6599c47c992c778e08b054daecc2540d57929e4ab1fd
  ubuntu-24.04-live-server-amd64:
    url: "https://releases.ubuntu.com/noble/ubuntu-24.04-live-server-amd64.iso"
    #sha256: 8762f7e74e4d64d72fceb5f70682e6b069932deedb4949c6975d0f0fe0a91be3
  ubuntu-24.04-desktop-amd64:
    url: "https://releases.ubuntu.com/noble/ubuntu-24.04-desktop-amd64.iso"
    #sha256: 81fae9cc21e2b1e3a9a4526c7dad3131b668e346c580702235ad4d02645d9455
