menus:
  - id: ubuntu-24.04-live-server-amd64
    menu_text: "Install Ubuntu 24.04 LTS with autoinstaller (MAC: ${mac_addr})"
    # Specify the id of images.<id>
    image_id: "ubuntu-24.04-live-server-amd64"

  - id: ubuntu-24.04-live-server-amd64-common
    menu_text: "Install Ubuntu 24.04 LTS"
    image_id: "ubuntu-24.04-live-server-amd64"

  - id: ubuntu-24.04-desktop-amd64-common
    menu_text: "Install Ubuntu 24.04 LTS desktop"
    image_id: "ubuntu-24.04-desktop-amd64"

autoinstalls:
  # Template will be copied on the image-server "/os/autoinstall/${id}/user-data".
  - id: common
    template: common.yml.j2

  - id: 52:54:ff:00:00:01
    # This program will search templates under the directory template/
    template: autoinstall_by_mac.yml.j2
    # Args will be passed when the template is rendered.
    args:
      hostname: ubuntu-server
      network:
        ethernets:
          enp1s0:
            dhcp4: false
            dhcp6: false
            addresses:
              - 192.168.1.11/24
            gateway4: 192.168.1.1
            nameservers:
              addresses: ["192.168.1.1", "8.8.8.8", "8.8.4.4"]
          enp2s0:
            addresses:
              - 172.28.0.1/16
            dhcp4: false
            dhcp6: false

# images.<id_of_image>.url
images:
  ubuntu-24.04-live-server-amd64:
    url: "https://releases.ubuntu.com/noble/ubuntu-24.04-live-server-amd64.iso"
    #sha256: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  ubuntu-24.04-desktop-amd64:
    url: "https://releases.ubuntu.com/noble/ubuntu-24.04-desktop-amd64.iso"
    #sha256: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
